### ISSUE TITLE
Documentation: error when following README example

### ISSUE THREAD

**Issue by martinctc** [Azure/AzureContainers#15]
Hi there, thank you for creating this package. I've tried following the example on the README, but run into an error for the following line: 

```R
acr <- resgroup$create_acr("myacr", location="australiaeast")
```

```
Error: attempt to apply non-function
```
I'm unable to find the documentation for `create_acr`, or figure out what is missing - can anyone help? Thank you!

**Comment by hongooi73** [comment]
Hi there Martin,

Did you forget to run `library(AzureContainers)`?
