### ISSUE TITLE
Example for using env_vars in create_aci function

### ISSUE THREAD

**Issue by dareneiri** [Azure/AzureContainers#16]
Can you please provide an example for using the `env_vars` argument in the `create_aci` function? I can't seem to get that to work. When I do not use `env_vars` I can use the function fine.

**Comment by hongooi73** [comment]
It looks like the syntax for the REST API call has changed. I'll fix this for the next release. In the meantime, see if adding `api_version="2018-09-01"` to the `create_aci` call helps.

**Comment by hongooi73** [comment]
Actually, this appears to be a genuine bug in `create_aci()`.
